{{- if .Values.app.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mj25-wedding.fullname" . }}-data
  labels:
    {{- include "mj25-wedding.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.app.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.size }}
  {{- if .Values.app.persistence.storageClass }}
  storageClassName: {{ .Values.app.persistence.storageClass }}
  {{- end }}
{{- end }}
