apiVersion: v1
kind: Service
metadata:
  name: {{ include "mj25-wedding.fullname" . }}
  labels:
    {{- include "mj25-wedding.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.app.networking.webPort }}
      {{- end }}
  selector:
    {{- include "mj25-wedding.selectorLabels" . | nindent 4 }}
