name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Optimize images
        run: npm run images:optimize || true

      - name: Commit optimized assets (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/assets || true
          git add src/generated/hero-manifest.json || true
          if ! git diff --staged --quiet; then
            git commit -m "chore(images): add optimized hero assets [skip ci]" || true
            git push origin HEAD:main || true
          else
            echo "No image changes to commit"
          fi

      - name: Run tests
        run: npm test --silent

      - name: Build
        run: npm run build
